import type {Metadata} from "next";
import "./globals.css";
import Header from "./ui/Header";
import Providers from "./Providers";
import React from "react";
import {ThemeProvider} from "next-themes";
import {Inter} from "next/dist/compiled/@next/font/dist/google";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
config.autoAddCss = false;

export const metadata: Metadata = {
    title: "INSIGHT NEWS",
    description: "Generated by create next app",
    icons: {
        icon: 'icon.png'
    }
};



export default function RootLayout({children,}: { children: React.ReactNode; }) {
    return (
        <html lang="en" >


            <body className='bg-gray-100 dark:bg-zinc-900 transition-all duration-700'>
            <Providers >
            <Header/>
            <div className='max-w-6xl mx-auto'>{children}</div>
            </Providers>

            </body>
        </html>
    );
}
