import type {Metadata} from "next";
import "./globals.css";
import Header from "./ui/Header";
import Providers from "./Providers";
import React from "react";



export const metadata: Metadata = {
    title: "INSIGHT NEWS",
    description: "Generated by create next app",
    icons:{
        icon:'icon.png'
    }
};

export default function RootLayout({children,}: { children: React.ReactNode; }) {
    return (
        <html >

        <Providers>

            <body className='bg-gray-100 dark:bg-zinc-900 transition-all duration-700'>
            <Header/>
            <div className='max-w-6xl mx-auto'>{children}</div>
            </body>
        </Providers>

        </html>
    );
}
