import {Metadata} from "next";
import fetchNews from "../lib/fetchNews";
import {categories} from "../constants";
import NewsList from "./ui/NewsList";

export const metadata: Metadata = {
    title: "INSIGHT NEWS",
    description: "Generated by create next app",
    icons:{
        icon:'icon.png'
    }
};



 async function Home() {

    const news : NewsResponse = await fetchNews(categories.join(","))
  return (
    <div>
     <NewsList news={news}/>
    </div>
  );
}
export  default Home;
