import {Metadata} from "next";
import fetchNews from "../lib/fetchNews";
import {categories} from "../constants";
import NewsList from "./ui/NewsList";
import React, {Suspense} from "react";
import Loading from "./loading";
import Error from './error';

// export const metadata: Metadata = {
//     title: "INSIGHT NEWS",
//     description: "Generated by create next app",
//     icons:{
//         icon:'icon.png'
//     }
// };



 async function Home() {

    const news : NewsResponse = await fetchNews(categories.join(","))
  return (
    <div>
        <Suspense fallback={<Loading/>}>

            <NewsList news={news}/>

        </Suspense>
    </div>
  );
}
export  default Home;
