import type {Metadata} from "next";
import "../globals.css";
import Header from "../ui/Header";
import Providers from "../Providers";
import React from "react";
import {ChatBubbleOvalLeftEllipsisIcon} from "@heroicons/react/24/solid";
import ChatBoxIcon from "../ui/ChatBoxIcon";


export const metadata: Metadata = {
    title: "INSIGHT NEWS",
    description: "Generated by create next app",
    icons: {
        icon: 'icon.png'
    }
};

export default function RootLayout({children,}: { children: React.ReactNode; }) {
    return (


        <>
            <div className='max-w-6xl mx-auto'>{children}</div>


        </>


    );
}
